global:
  scrape_interval: 10s
scrape_configs:
 - job_name: prometheus
   static_configs:
    - targets:
       - prometheus:9090
 - job_name: dramatiq-worker
   metrics_path: /
   static_configs:
    - targets:
       - worker:9191
 - job_name: web-worker
   static_configs:
    - targets:
       - web:8000
